version: '3'

services:
  web:
    build: ./web/
    container_name: myphp
    ports:
      - "80:80"
    volumes:
      - ./web/src:/var/www
    links:
      - db

  db:
    image: mysql:latest 
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=mydb
      - MYSQL_USER=mysql
      - MYSQL_PASSWORD=mysql
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - ./db/data/:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: myphpadmin
    ports:
      - "8080:80"
    links:
      - db

volumes:
  php:
  db:
